
- hosts: all  
  roles:
  - role: stephdewit.nvm
    nvm_version: 'latest'
    nvm_node_version: '10.4.0'

- hosts: all
  roles:
    - ubuntu/apt
    - ubuntu/zsh
    - common/robo3t
    - common/reactotron
    - common/fira-code-font
    - ubuntu/homebrew

- hosts: all
  roles:
    - role: gantsign.postman

- hosts: all
  vars:
    inotify_max_user_watches: 524288
  roles:
    - ubuntu/inotify

- hosts: all
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_env.USER }}"
# change default shell to user
- hosts: all
  tasks:
    - name: Change default shell to user
      shell: chsh -s /bin/zsh